// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6ICNTv9EJfstbyuP0WlqQLlbeBC09rbo',
    appId: '1:614390984598:web:147ab30ea6fdd209dbf7b7',
    messagingSenderId: '614390984598',
    projectId: 'quick-pointer-355409',
    authDomain: 'quick-pointer-355409.firebaseapp.com',
    storageBucket: 'quick-pointer-355409.firebasestorage.app',
    measurementId: 'G-QQ7SWR1F78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN7yNdn8qEBP2fwLe5NWu9FFylfAKt4pE',
    appId: '1:614390984598:android:482940f29cc4b7b9dbf7b7',
    messagingSenderId: '614390984598',
    projectId: 'quick-pointer-355409',
    storageBucket: 'quick-pointer-355409.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOc2jSVZ6aqGBqYhmmBdnzzZQvO1Rd490',
    appId: '1:614390984598:ios:5b73316b8d474795dbf7b7',
    messagingSenderId: '614390984598',
    projectId: 'quick-pointer-355409',
    storageBucket: 'quick-pointer-355409.firebasestorage.app',
    iosBundleId: 'com.example.tasteBudsUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOc2jSVZ6aqGBqYhmmBdnzzZQvO1Rd490',
    appId: '1:614390984598:ios:5b73316b8d474795dbf7b7',
    messagingSenderId: '614390984598',
    projectId: 'quick-pointer-355409',
    storageBucket: 'quick-pointer-355409.firebasestorage.app',
    iosBundleId: 'com.example.tasteBudsUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr3lmlMXb9MYYE2WN6uXPvWnJczlySdT0',
    appId: '1:614390984598:web:987da12c06aac19edbf7b7',
    messagingSenderId: '614390984598',
    projectId: 'quick-pointer-355409',
    authDomain: 'quick-pointer-355409.firebaseapp.com',
    storageBucket: 'quick-pointer-355409.firebasestorage.app',
    measurementId: 'G-GRBEKXMYWT',
  );
}
